
    // Sample post data
    const posts = [
    { 

      date: '2024-02-07', 
      post: "When you reach the end of your rope, tie a knot in it and hang on.Well done is better than well said..",
      seen:'3 388',
      shares:'8',
      copies:'13',
    },
    {
      date: '2024-02-06', 
      post: "Setting goals is the first step in turning the invisible into the visible.",
      seen:'3 388',
      shares:'21',
      copies:'48',
    },
    {
      date: '2024-02-05', 
      post: "Look up at the stars and not down at your feet. Try to make sense of what you see, and wonder about what makes the universe exist. Be curious.",
      seen:'3 388',
      shares:'268',
      copies:'122',
    },
    {
      date: '2024-02-04', 
      post: "The key is to keep company only with people who uplift you, whose presence calls forth your best.",
      seen:'3 388',
      shares:'281',
      copies:'23',
    },
    {
      date: '2024-02-03', 
      post: "Aim for the moon. If you miss, you may hit a star.",
      seen:'3 388',
      shares:'298',
      copies:'9',
    },
    {
      date: '2024-02-02', 
      post: "You can't cross the sea merely by standing and staring at the water.",
      seen:'3 388',
      shares:'322',
      copies:'29',
    },
    {
      date: '2024-02-01', 
      post: "There is only one corner of the universe you can be certain of improving, and that's your own self.",
      seen:'391',
      shares:'948',
      copies:'43',
    },
    {
      date: '2024-01-31', 
      post: "What you get by achieving your goals is not as important as what you become by achieving your goals.",
      seen:'388',
      shares:'108',
      copies:'40',
    },
    {
      date: '2024-01-30', 
      post: "Don't watch the clock; do what it does. Keep going.",
      seen:'3 388',
      shares:'38',
      copies:'98',
    },
    {
      date: '2024-01-29', 
      post: "Your talent is God's gift to you. What you do with it is your gift back to God.",
      seen:'3 388',
      shares:'8',
      copies:'51',
    },
    {
      date: '2024-01-28', 
      post: "Consult not your fears but your hopes and your dreams. Think not about your frustrations, but about your unfulfilled potential. Concern yourself not with what you tried and failed in, but with what it is still possible for you to do.",
      seen:'3 388',
      shares:'170',
      copies:'997',
    },
    {
      date: '2024-01-27', 
      post: "There is only one corner of the universe you can be certain of improving, and that's your own self.",
      seen:'3 388',
      shares:'2',
      copies:'78',
    },
    {
      date: '2024-01-26', 
      post: "Knowing is not enough; we must apply. Willing is not enough; we must do.",
      seen:'3 388',
      shares:'1',
      copies:'12',
    },
    {
      date: '2024-01-25', 
      post: "What you get by achieving your goals is not as important as what you become by achieving your goals.",
      seen:'3 388',
      shares:'68',
      copies:'89',
    },
    {
      date: '2024-01-24', 
      post: "Don't watch the clock; do what it does. Keep going..",
      seen:'3 388',
      shares:'95',
      copies:'106',
    },
    {
      date: '2024-01-23', 
      post: "Your talent is God's gift to you. What you do with it is your gift back to God.",
      seen:'3 388',
      shares:'8',
      copies:'23',
    },
    {
      date: '2024-01-22', 
      seen:'3 388',
      shares:'5',
      copies:'13',
      post: "The secret of getting ahead is getting started.",
    },
    {
      date: '2024-01-21', 
      post: "Start where you are. Use what you have. Do what you can while Keeping your eyes on the stars, and your feet on the ground..",
      seen:'3 388',
      shares:'33',
      copies:'50',
    },
    {
      date: '2024-01-20', 
      post: "Do the difficult things while they are easy and do the great things while they are small. A journey of a thousand miles must begin with a single step.",
      seen:'3 388',
      shares:'19',
      copies:'45',
    },
    {
      date: '2024-01-19', 
      post: "A good plan violently executed now is better than a perfect plan executed next week.",
      seen:'3 388',
      shares:'4',
      copies:'13',
    },
    {
      date: '2024-01-18', 
      post: "If you can dream it, you can do it.What you do today can improve all your tomorrows.",
      seen:'3 388',
      shares:'2',
      copies:'27',
    },
    {
      date: '2024-01-17', 
      post: "Life is 10% what happens to you and 90% how you react to it.",
      seen:'3 388',
      shares:'13',
      copies:'38',
    },
    {
      date: '2024-01-16', 
      post: "Failure will never overtake me if my determination to succeed is strong enough.",
      seen:'3 388',
      shares:'2',
      copies:'57',
    },
    {
      date: '2024-01-16', 
      post: "When something is important enough, you do it even if the odds are not in your favor.",
      seen:'3 388',
      shares:'28',
      copies:'57',
    },
    {
      date: '2024-01-15', 
      post: "Quality is not an act, it is a habit.",
      seen:'3 388',
      shares:'8',
      copies:'13',
    },
    {
      date: '2024-01-14', 
      post: "With the new day comes new strength and new thoughts.",
      seen:'3 388',
      shares:'2',
      copies:'19',
    },
    {
      date: '2024-01-13', 
      post: "Believe in yourself! Have faith in your abilities! Without a humble but reasonable confidence in your own powers you cannot be successful or happy.",
      seen:'38',
      shares:'2948',
      copies:'63',
    },
    {
      date: '2024-01-12', 
      post: "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.",
      seen:'3 388',
      shares:'6',
      copies:'19',
    },
    {
      date: '2024-01-11', 
      post: "Ever tried. Ever failed. No matter. Try Again. Fail again. Fail better.",
      seen:'3 388',
      shares:'2',
      copies:'17',
    },
    {
      date: '2024-01-10', 
      post: "If you're going through hell, keep going.",
      seen:'3 388',
      shares:'3',
      copies:'23',
    },
    {
      date: '2024-01-09', 
      post: "Good, better, best. Never let it rest. 'Til your good is better and your better is best.",
      seen:'3 388',
      shares:'4',
      copies:'18',
    },
    {
      date: '2024-01-08', 
      post: "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.",
      seen:'3 388',
      shares:'2',
      copies:'5',
    },
    {
      date: '2024-01-07', 
      post: "It always seems impossible until it's done.",
      seen:'8',
      shares:'1',
      copies:'6',
    },
    {
      date: '2024-01-06', 
      post: "It does not matter how slowly you go as long as you do not stop.",
      seen:'3 388',
      shares:'9',
      copies:'25',
    },
    {
      date: '2024-01-05', 
      post: "People Isolate Themselves For Bigger Reasons Than They Care To Explain. Give Em Space",
      seen:'3 388',
      shares:'2',
      copies:'12',
    },
     {
       date: '2024-01-04',
       post: "To Create Generational Wealth, You Have To Take Risks And Move Differently.",
      seen:'3 388',
      shares:'28',
      copies:'99',
     },    
     {
       date: '2024-01-03',
       post: "Get RID Of Everybody That Play BOTH sides.✂️ 2024",
       seen:'3 388',
      shares:'13',
      copies:'27',
     },
     {
       date: '2024-01-02',
       post: "People Isolate Themselves For Bigger Reasons Than They Care To Explain. Give Em Space",
           seen:'3 388',
      shares:'8',
      copies:'16',
     },
     {
       date: '2024-01-01',
       post: "Goodbye to all the drama & pain of 2023. Hello to the Peace, Joy & Miracles of 2024.",
      seen:'3 388',
      shares:'2948',
      copies:'13',
     },


///2023
     {
        date: '2023-12-18',
        post: "trust your intuition, it never lies. don't be afraid to be alone that's where ideas are formulated. ❤️ & as you Pray constantly, that's where answers to life are found.❤️🙏",
            seen:'3 388',
      shares:'2948',
      copies:'13',
      },
      {
        date: '2023-12-19',
        post: "Don't compete, don't compare, run your own race in your own lane at your own pace. You’ll always be happy!!♥️",
            seen:'3 388',
      shares:'2948',
      copies:'13',
      },
      {
        date: '2023-12-20',
        post: "A few bad chapters does not mean your story is over. Be strong Champ❤️🙏🏾",
            seen:'3 388',
      shares:'2948',
      copies:'13',
      },
      {
        date: '2023-12-21',
        post: "The pride is inside you, but courage you have to create it inside yourself, and fear will Always attacks you, but don't allow that.♥️",
            seen:'3 388',
      shares:'2948',
      copies:'13',
      },
      {
        date: '2023-12-22',
        post: "Remember not to compare yourself to others. Every one has a unique path to go down. It's important to continue on your journey & focus on your own progress, rather than trying to measure yourself against others.",
            seen:'3 388',
      shares:'2948',
      copies:'13',
      },
      {
        date: '2023-12-23',
        post: "Look foward with Hope & Don't look back with Regret",
            seen:'3 388',
      shares:'2948',
      copies:'13',
      },
      {
        date: '2023-12-24',
        post: "Right now be grateful for your life. Give God a thank you for creating you. Tell him you thank him for giving you life everyday. Happy sunday & cristmas eve ",
            seen:'3 388',
      shares:'2948',
      copies:'13',
      },
      {
        date: '2023-12-25',
        post: "Everyone leaves. Learn how to survive alone❤️ . Merry CristMas Everyone",
              seen:'3 388',
      shares:'2948',
      copies:'13',
      },
      {
        date: '2023-12-26',
        post: "Are you upset about how your life went this year? well god is preparing you for a better year.",
              seen:'3 388',
      shares:'2948',
      copies:'13',
       },
      {
        date: '2023-12-27',
        post: "observe and do not tolerate because it will effects your standards, don't let them down . make yourself indispensable by providing value beyond expectations ",
              seen:'3 388',
      shares:'2948',
      copies:'13',    
        },
      {
        date: '2023-12-28',
        post: "challenge yourself daily to become a better version of yourself because life is so subtle sometimes that you barely notice yourself walking through the doors you once prayed would open.",
              seen:'3 388',
      shares:'2948',
      copies:'13',
         },
      {
        date: '2023-12-29',
        post: "sometimes u have to make a decision that breaks your heart but gives u peace❤ & how ever anything you lose by speaking your truth isn’t a loss, it’s an alignment. 🗣️.",
              seen:'3 388',
      shares:'2948',
      copies:'13',
      },
      {
        date: '2023-12-30',
        post: "🌟 courage defines triumph! 💫💪 ' success is not final, failure is not fatal: it is the courage to continue that counts.'🚀✨ these powerful words remind us that success isn't the end and failure isn't the end-all-be-all. it's the resilience to persist that truly matters! 💡💖.",
              seen:'3 388',
      shares:'2948',
      copies:'13',
      },
      {
        date: '2023-12-31',
        post: "don't forget to pray for a better new year🌟",
              seen:'3 388',
      shares:'2948',
      copies:'13',
      
      },

    ];
    
    //“ forever ” comes with sacrifices ‚ compromises ‚ forgiveness & tears .